import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./componants/navbar";
import CursorFollower from "./componants/CursorFollower";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`!bg-white overflow-x-hidden w-full`}
        >
        <CursorFollower />
        <Navbar/>

        {children}
      </body>
    </html>
  );
}
